export const ADDRECIPE_LOADING = "ADDRECIPE_LOADING";
export const ADDRECIPE_SUCCESS = "ADDRECIPE_SUCCESS";
export const ADDRECIPE_ERROR = "ADDRECIPE_ERROR";

export const GET_FEED_LOADING = "GET_FEED_LOADING";
export const GET_FEED_SUCCESS = "GET_FEED_SUCCESS";
export const GET_FEED_ERROR = "GET_FEED_ERROR";